#ifndef StatsEnums_Included
#define StatsEnums_Included

#define PER_CORE_STATS_ENUM_START 5000
#define PER_CORE_STATS_ENUM_FIRST 5001

enum StatisticsEnum
{
PCIE_GOODPUT_BASE,
AVG_PCIE_GOODPUT,
PCIE_FLIT_BASE,
AVG_PCIE_PHYS_LATENCY,
PCIE_TXTRANS_BASE,
AVG_PCIE_TXTRANS_LATENCY,
PCIE_TXDLL_BASE,
AVG_PCIE_TXDLL_LATENCY,
PCIE_RXDLL_BASE,
AVG_PCIE_RXDLL_LATENCY,
PCIE_RXTRANS_BASE,
AVG_PCIE_RXTRANS_LATENCY,


CORE_STATS_START = PER_CORE_STATS_ENUM_START,
	StatisticsEnumEnd
};
#endif //StatsEnums_Included
